Add SocketPath/PciID to Interface struct
containernetworking/cni pull request #1069
Opened 2024-02-19 16:39 UTC by MikeZappa87

This is to resolve: #1050

2024-02-26 15:38 UTC, squeed commented
Looks good; we need to add this to the spec, though.

2024-02-26 15:39 UTC, MikeZappa87 commented
> Looks good; we need to add this to the spec, though.

I can start on that right now.

2024-02-26 16:06 UTC, squeed commented on pkg/types/100/types_test.go
> +			"pci_id": 	 "8086:9a01",
nit: spacing here seems off?

2024-02-26 17:39 UTC, tamilmani1989 approved these changes
lgtm

2024-03-04 16:10 UTC, s1061123 requested changes

2024-03-04 16:10 UTC, s1061123 commented on SPEC.md
> +    - `pci_id` (string): The combination of vendor id and device id to uniquely identify a device.
Could you change go convention, as camel case? (i.e. socketPath / pciID)

2024-03-04 16:11 UTC, squeed commented on SPEC.md
> +    - `socket_path` (string): The path of the socket that can be passed down to OCI runtimes.
```suggestion
    - `socket_path` (string, optional): An absolute path to a socket file corresponding to this interface, if applicable.
```

2024-03-04 16:12 UTC, squeed commented on SPEC.md
> +    - `pci_id` (string): The combination of vendor id and device id to uniquely identify a device.
```suggestion
    - `pciID` (string, optional): The platform-specific identifier of the PCI device corresponding to this interface, if applicable.
```

2024-03-04 16:27 UTC, s1061123 approved these changes

2024-03-04 16:41 UTC, merged