Minor CNI v1.1 api fixes
containernetworking/cni pull request #1071
Opened 2024-03-04 16:01 UTC by squeed

A few small things I discovered I needed while implementing spec v1.1 for the plugins.

2024-03-04 22:04 UTC, henry118 commented on pkg/types/types.go
> +type GCAttachment struct {
Suggest including a doc here for the type

2024-03-05 12:26 UTC, s1061123 requested changes

2024-03-11 20:37 UTC, squeed commented
@henry118 @s1061123 fixed, PTAL

2024-03-11 21:34 UTC, henry118 approved these changes
LGTM

2024-03-18 14:40 UTC, MikeZappa87 approved these changes

2024-03-19 10:31 UTC, s1061123 approved these changes
LGTM!

2024-03-19 10:36 UTC, merged