Extend capabilities with cgroup path
containernetworking/cni pull request #936
Opened 2022-12-06 05:19 UTC by aditighag

Container runtimes can pass pod cgroup paths
when requested by CNI plugins.

Details around the use cases for this field are
documented - https://github.com/kubernetes/kubernetes/issues/113342.

Signed-off-by: Aditi Ghag <aditi@cilium.io>

2022-12-12 16:56 UTC, squeed approved these changes

2023-02-08 16:24 UTC, squeed requested changes

2023-02-08 16:24 UTC, squeed commented on CONVENTIONS.md
> +| cgroup path | Provide the cgroup path for pod as requested by CNI plugins. | `cgroupPath` | `cgroupPath` (string entry). <pre>"/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-burstable.slice
The example should actually be `/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod1735c29c_32af_407c_aa34_9ec25fbef089.slice`

2023-02-08 16:33 UTC, MikeZappa87 approved these changes

2023-02-09 10:44 UTC, squeed approved these changes

2023-02-09 10:44 UTC, merged